config/routes.rb
UnitTestingHomework::Application.routes.draw do
  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :price, :status
  before_save :set_defaults
end

#first test
PROPOSED = 0

#second test
private
def set_defaults
  self.status = 0
  self.price = 0


#third test
def accept
  if @self.price == 0
    return false
  else
    self.status = 1
    return true
  end
end

#fourth test. Just because its a constant, doesn't mean it has to be one or zero.
def accept
  if self.price = 0
    return false
  else
    self.status = 1
    return true
  end
end

  def PROPOSED
    self.status = 0
  end

  def QUEUED
    self.status = 1
  end

  def PRODUCTION
    self.status = 2
  end

  def TESTING
    self.status = 3
  end

  def CLOSED
    self.status = 4
  end

  def CANCELLED
    self.status = 5
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<table>
  <tr>
    <th>Status</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.status %></td>
    <td><%= job.price %></td>
    <td><%= link_to 'Show', job %></td>
    <td><%= link_to 'Edit', edit_job_path(job) %></td>
    <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @job.status %>
</p>

<p>
  <b>Price:</b>
  <%= @job.price %>
</p>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UnitTestingHomework</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>